<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**" />
    <None Remove="tests/**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\logger\EasyLog.csproj" />
  </ItemGroup>

    <ItemGroup>
	    <PackageReference Include="System.Management" Version="10.0.8" />
    </ItemGroup>

</Project>
