//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.CLI.Ressources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddSave {
            get {
                return ResourceManager.GetString("AddSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Software App :.
        /// </summary>
        public static string BuisinessSoftware {
            get {
                return ResourceManager.GetString("BuisinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name to add (e.g. Calculator.exe):.
        /// </summary>
        public static string BusinessSoftwareAskAdd {
            get {
                return ResourceManager.GetString("BusinessSoftwareAskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name to remove (e.g. Calculator.exe):.
        /// </summary>
        public static string BusinessSoftwareAskRemove {
            get {
                return ResourceManager.GetString("BusinessSoftwareAskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software detected: complete backup save blocked..
        /// </summary>
        public static string BusinessSoftwareDetectedSaveBlocked {
            get {
                return ResourceManager.GetString("BusinessSoftwareDetectedSaveBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a process.
        /// </summary>
        public static string BusinessSoftwareMenuAdd {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched processes:.
        /// </summary>
        public static string BusinessSoftwareMenuList {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a process.
        /// </summary>
        public static string BusinessSoftwareMenuRemove {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software configuration.
        /// </summary>
        public static string BusinessSoftwareMenuTitle {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose App Language :.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No job IDs. Use --help.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension To Encrypt :.
        /// </summary>
        public static string ExtensionsToEncrypt {
            get {
                return ResourceManager.GetString("ExtensionsToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension to add (e.g. exe, txt, ...):.
        /// </summary>
        public static string ExtensionsToEncryptAskAdd {
            get {
                return ResourceManager.GetString("ExtensionsToEncryptAskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension to remove (e.g. exe, txt, ...):.
        /// </summary>
        public static string ExtensionsToEncryptAskRemove {
            get {
                return ResourceManager.GetString("ExtensionsToEncryptAskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an extension.
        /// </summary>
        public static string ExtensionsToEncryptMenuAdd {
            get {
                return ResourceManager.GetString("ExtensionsToEncryptMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions that will be encrypted in the backup:.
        /// </summary>
        public static string ExtensionsToEncryptMenuList {
            get {
                return ResourceManager.GetString("ExtensionsToEncryptMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an extension.
        /// </summary>
        public static string ExtensionsToEncryptMenuRemove {
            get {
                return ResourceManager.GetString("ExtensionsToEncryptMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption menu.
        /// </summary>
        public static string ExtensionsToEncryptMenuTitle {
            get {
                return ResourceManager.GetString("ExtensionsToEncryptMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number: please enter a number between 1 and 5.
        /// </summary>
        public static string InvalidSaveIndex {
            get {
                return ResourceManager.GetString("InvalidSaveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language menu.
        /// </summary>
        public static string LanguageMenuTitle {
            get {
                return ResourceManager.GetString("LanguageMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large file threshold.
        /// </summary>
        public static string LargeFileThreshold {
            get {
                return ResourceManager.GetString("LargeFileThreshold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log Format :.
        /// </summary>
        public static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string LogFormatJson {
            get {
                return ResourceManager.GetString("LogFormatJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log format menu.
        /// </summary>
        public static string LogFormatMenuTitle {
            get {
                return ResourceManager.GetString("LogFormatMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected log format.
        /// </summary>
        public static string LogFormatSelected {
            get {
                return ResourceManager.GetString("LogFormatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string LogFormatText {
            get {
                return ResourceManager.GetString("LogFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string LogFormatXml {
            get {
                return ResourceManager.GetString("LogFormatXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a complete backup save.
        /// </summary>
        public static string MainMenuCompleteSave {
            get {
                return ResourceManager.GetString("MainMenuCompleteSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a differential backup save.
        /// </summary>
        public static string MainMenuDifferentialSave {
            get {
                return ResourceManager.GetString("MainMenuDifferentialSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainMenuExit {
            get {
                return ResourceManager.GetString("MainMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ New Job.
        /// </summary>
        public static string NewJob {
            get {
                return ResourceManager.GetString("NewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command arguments detected..
        /// </summary>
        public static string NoArgsWarning {
            get {
                return ResourceManager.GetString("NoArgsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software.
        /// </summary>
        public static string OptionMenuBusinessSoftware {
            get {
                return ResourceManager.GetString("OptionMenuBusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions to encrypt.
        /// </summary>
        public static string OptionMenuExtensionsToEncrypt {
            get {
                return ResourceManager.GetString("OptionMenuExtensionsToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string OptionMenuLanguage {
            get {
                return ResourceManager.GetString("OptionMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log format.
        /// </summary>
        public static string OptionMenuLogFormat {
            get {
                return ResourceManager.GetString("OptionMenuLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        public static string OptionMenuLogOutput {
            get {
                return ResourceManager.GetString("OptionMenuLogOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where should the logs be written?.
        /// </summary>
        public static string OptionMenuLogOutputQuestion {
            get {
                return ResourceManager.GetString("OptionMenuLogOutputQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State file.
        /// </summary>
        public static string OptionMenuStateOutput {
            get {
                return ResourceManager.GetString("OptionMenuStateOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where should the state information be written?.
        /// </summary>
        public static string OptionMenuStateOutputQuestion {
            get {
                return ResourceManager.GetString("OptionMenuStateOutputQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option menu.
        /// </summary>
        public static string OptionMenuTitle {
            get {
                return ResourceManager.GetString("OptionMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Settings.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit....
        /// </summary>
        public static string PressToExit {
            get {
                return ResourceManager.GetString("PressToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority extensions.
        /// </summary>
        public static string PriorityExtensions {
            get {
                return ResourceManager.GetString("PriorityExtensions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Progess.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which save(s) do you want to run?.
        /// </summary>
        public static string PromptSelection {
            get {
                return ResourceManager.GetString("PromptSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Return to previous menu.
        /// </summary>
        public static string ReturnToPreviousMenu {
            get {
                return ResourceManager.GetString("ReturnToPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute All.
        /// </summary>
        public static string RunAll {
            get {
                return ResourceManager.GetString("RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Selected.
        /// </summary>
        public static string RunSelected {
            get {
                return ResourceManager.GetString("RunSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in progress....
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Editor.
        /// </summary>
        public static string SaveEditor {
            get {
                return ResourceManager.GetString("SaveEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup save failed..
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about backup save.
        /// </summary>
        public static string SaveInfosMenuTitle {
            get {
                return ResourceManager.GetString("SaveInfosMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where would you like to put the backup save?.
        /// </summary>
        public static string SaveMenuAskSaveDst {
            get {
                return ResourceManager.GetString("SaveMenuAskSaveDst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to name this backup save?.
        /// </summary>
        public static string SaveMenuAskSaveName {
            get {
                return ResourceManager.GetString("SaveMenuAskSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to save?.
        /// </summary>
        public static string SaveMenuAskSaveSrc {
            get {
                return ResourceManager.GetString("SaveMenuAskSaveSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;1&quot; for save spot one, &quot;1;3&quot; for save spots one and three or &quot;1-3&quot; for save spots one to three..
        /// </summary>
        public static string SaveMenuDetails {
            get {
                return ResourceManager.GetString("SaveMenuDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On which save(s) would you like to perform the action ?.
        /// </summary>
        public static string SaveMenuTitle {
            get {
                return ResourceManager.GetString("SaveMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of backup save.
        /// </summary>
        public static string SaveStart {
            get {
                return ResourceManager.GetString("SaveStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup save finished successfully..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete backup save.
        /// </summary>
        public static string SaveTypeComplete {
            get {
                return ResourceManager.GetString("SaveTypeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential backup save.
        /// </summary>
        public static string SaveTypeDifferential {
            get {
                return ResourceManager.GetString("SaveTypeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which type of backup save would you like to perform ?.
        /// </summary>
        public static string SaveTypeMenuTitle {
            get {
                return ResourceManager.GetString("SaveTypeMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
