//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.GUI.Ressources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string AddSave {
            get {
                return ResourceManager.GetString("AddSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business Software App :.
        /// </summary>
        public static string BuisinessSoftware {
            get {
                return ResourceManager.GetString("BuisinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process name to add (e.g. CalculatorApp):.
        /// </summary>
        public static string BusinessSoftwareAskAdd {
            get {
                return ResourceManager.GetString("BusinessSoftwareAskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process name to remove:.
        /// </summary>
        public static string BusinessSoftwareAskRemove {
            get {
                return ResourceManager.GetString("BusinessSoftwareAskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business software detected: complete backup save blocked..
        /// </summary>
        public static string BusinessSoftwareDetectedSaveBlocked {
            get {
                return ResourceManager.GetString("BusinessSoftwareDetectedSaveBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a process.
        /// </summary>
        public static string BusinessSoftwareMenuAdd {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (none).
        /// </summary>
        public static string BusinessSoftwareMenuEmpty {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watched processes:.
        /// </summary>
        public static string BusinessSoftwareMenuList {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove a process.
        /// </summary>
        public static string BusinessSoftwareMenuRemove {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business software configuration.
        /// </summary>
        public static string BusinessSoftwareMenuTitle {
            get {
                return ResourceManager.GetString("BusinessSoftwareMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose App Language :.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        public static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: No job IDs. Use --help.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension To Encrypt :.
        /// </summary>
        public static string ExtensionsToEncrypt {
            get {
                return ResourceManager.GetString("ExtensionsToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid number: please enter a number between 1 and 5.
        /// </summary>
        public static string InvalidSaveIndex {
            get {
                return ResourceManager.GetString("InvalidSaveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language menu.
        /// </summary>
        public static string LanguageMenuTitle {
            get {
                return ResourceManager.GetString("LanguageMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log Format :.
        /// </summary>
        public static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON.
        /// </summary>
        public static string LogFormatJson {
            get {
                return ResourceManager.GetString("LogFormatJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log format menu.
        /// </summary>
        public static string LogFormatMenuTitle {
            get {
                return ResourceManager.GetString("LogFormatMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected log format.
        /// </summary>
        public static string LogFormatSelected {
            get {
                return ResourceManager.GetString("LogFormatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        public static string LogFormatText {
            get {
                return ResourceManager.GetString("LogFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML.
        /// </summary>
        public static string LogFormatXml {
            get {
                return ResourceManager.GetString("LogFormatXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perform a complete backup save.
        /// </summary>
        public static string MainMenuCompleteSave {
            get {
                return ResourceManager.GetString("MainMenuCompleteSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perform a differential backup save.
        /// </summary>
        public static string MainMenuDifferentialSave {
            get {
                return ResourceManager.GetString("MainMenuDifferentialSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string MainMenuExit {
            get {
                return ResourceManager.GetString("MainMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        public static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ➕ New Job.
        /// </summary>
        public static string NewJob {
            get {
                return ResourceManager.GetString("NewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No command arguments detected..
        /// </summary>
        public static string NoArgsWarning {
            get {
                return ResourceManager.GetString("NoArgsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business software.
        /// </summary>
        public static string OptionMenuBusinessSoftware {
            get {
                return ResourceManager.GetString("OptionMenuBusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Languages.
        /// </summary>
        public static string OptionMenuLanguage {
            get {
                return ResourceManager.GetString("OptionMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log format.
        /// </summary>
        public static string OptionMenuLogFormat {
            get {
                return ResourceManager.GetString("OptionMenuLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option menu.
        /// </summary>
        public static string OptionMenuTitle {
            get {
                return ResourceManager.GetString("OptionMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚙️ Settings.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to exit....
        /// </summary>
        public static string PressToExit {
            get {
                return ResourceManager.GetString("PressToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progess.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which save(s) do you want to run?.
        /// </summary>
        public static string PromptSelection {
            get {
                return ResourceManager.GetString("PromptSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return to previous menu.
        /// </summary>
        public static string ReturnToPreviousMenu {
            get {
                return ResourceManager.GetString("ReturnToPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ▶▶  Run All.
        /// </summary>
        public static string RunAll {
            get {
                return ResourceManager.GetString("RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ▶  Run Selected.
        /// </summary>
        public static string RunSelected {
            get {
                return ResourceManager.GetString("RunSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save in progress....
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Editor.
        /// </summary>
        public static string SaveEditor {
            get {
                return ResourceManager.GetString("SaveEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup save failed..
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information about backup save.
        /// </summary>
        public static string SaveInfosMenuTitle {
            get {
                return ResourceManager.GetString("SaveInfosMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where would you like to put the backup save?.
        /// </summary>
        public static string SaveMenuAskSaveDst {
            get {
                return ResourceManager.GetString("SaveMenuAskSaveDst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How would you like to name this backup save?.
        /// </summary>
        public static string SaveMenuAskSaveName {
            get {
                return ResourceManager.GetString("SaveMenuAskSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What would you like to save?.
        /// </summary>
        public static string SaveMenuAskSaveSrc {
            get {
                return ResourceManager.GetString("SaveMenuAskSaveSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type &quot;1&quot; for save spot one, &quot;1;3&quot; for save spots one and three or &quot;1-3&quot; for save spots one to three..
        /// </summary>
        public static string SaveMenuDetails {
            get {
                return ResourceManager.GetString("SaveMenuDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On which save(s) would you like to perform the action ?.
        /// </summary>
        public static string SaveMenuTitle {
            get {
                return ResourceManager.GetString("SaveMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start of backup save.
        /// </summary>
        public static string SaveStart {
            get {
                return ResourceManager.GetString("SaveStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup save finished successfully..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete backup save.
        /// </summary>
        public static string SaveTypeComplete {
            get {
                return ResourceManager.GetString("SaveTypeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential backup save.
        /// </summary>
        public static string SaveTypeDifferential {
            get {
                return ResourceManager.GetString("SaveTypeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which type of backup save would you like to perform ?.
        /// </summary>
        public static string SaveTypeMenuTitle {
            get {
                return ResourceManager.GetString("SaveTypeMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stopped.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
